# Generated by Django 3.2.8 on 2021-10-15 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_currency_code', models.CharField(max_length=50)),
                ('from_currency_name', models.CharField(max_length=50)),
                ('to_currency_code', models.CharField(max_length=50)),
                ('to_currency_name', models.CharField(max_length=50)),
                ('exchange_rate', models.FloatField()),
                ('last_refreshed', models.DateTimeField()),
                ('time_zone', models.CharField(max_length=50)),
                ('bid_price', models.FloatField()),
                ('ask_price', models.FloatField()),
            ],
            options={
                'ordering': ['-last_refreshed'],
            },
        ),
    ]
